### ISSUE TITLE
Playlists list element margin issue

### ISSUE THREAD

**Issue by katspa-sc** [Trinovantes/userscript-youtube-playlist-organizer#15]
![image](https://user-images.githubusercontent.com/13397812/222925002-3b2e7098-02aa-4269-bb5b-30e3083a968a.png)
I've run into an issue with the playlists list being too much to the center of the screen, which results in the videos being obstructed.

I have disabled all extensions except Tampermonkey and all userscripts besides your creation but the problem persists.

Can this be fixed by editing the script itself? If so how?

Firefox 110.0.1
Tampermonkey 4.18.1
Windows 10

Also, great script :)

**Comment by Trinovantes** [comment]
This script was originally intended to be used on 1440p or higher displays 

I'll need to think about how to fix it for smaller displays

**Comment by katspa-sc** [comment]
It seems like you've fixed it in v2.2.0. Thanks for the swift response :) Can be considered closed from my standpoint, but idk if there are any TODOs left on this.

**Comment by Trinovantes** [comment]
Glad it worked
