### ISSUE TITLE
CSP blocks the script

### ISSUE THREAD

**Issue by dmitrybabich** [Trinovantes/userscript-youtube-playlist-organizer#20]
Due to the CSP headers, looks like changing DOM via VUE is not possible. As a workaround, this extension can be used

https://chromewebstore.google.com/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden?hl=en

**Comment by Trinovantes** [comment]
Vue 3.5.0 added trusted types so it should be fixed after I upgraded all the dependencies
